version: '3.8'

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "3"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - db
    logging: *default-logging
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./log:/app/log

  db:
    container_name: db
    image: postgres:15
    restart: always
    # for dev environment and demonstration, subject to change for production
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging: *default-logging

volumes:
  pgdata:
